Update, alphabetize AbstractEntryClient prints
dockstore/dockstore-cli pull request #180
Opened 2022-08-15 19:42 UTC by aofarrel

Updates `dockstore x --help` output.
* Arguments are now listed in alphabetical order
* Previously undocumented `nfl` argument is now included, but only when x=workflow
* WDL argument no longer incorrectly implies it's attached to a Docker image (seems to be a holdover from WDL tools being the norm)

Haven't run with unit tests yet hence draft.

2022-08-15 19:44 UTC, aofarrel commented
CircleCI is a docker pull timeout; if the issue my lacking of creds it may be need to be rerun by someone else.

2022-08-15 21:33 UTC, denis-yuen approved these changes

2022-08-16 16:45 UTC, coverbeck requested changes
I ran it and see this: 

>  list             :  lists all the Workflows published by the user
>
>
> nfl              :  returns the Nextflow Workflowdefintion for this entry
> publish          :  publish/unpublish a Workflow in Dockstore
> 
> refresh          :  updates your list of Workflows stored on Dockstore or an individual Workflow

1. Missing space before `definition` on the nfl line
2. The nfl line doesn't have two blank lines around it like all the other lines do.

2022-08-16 17:51 UTC, coverbeck approved these changes

2022-08-17 16:44 UTC, merged