Download CLI Jar at time of upgrade
dockstore/dockstore-cli pull request #42
Opened 2020-09-11 16:27 UTC by wshands

Downloads CLI Jar when CLI dockstore script is downloaded. Previously the Jar was not downloaded until the user ran the dockstore script.

The solution simply runs the newly downloaded dockstore script with the 'self-install' argument which checks to see if the proper CLI Jar has been downloaded to the user's system and if not the dockstore script downloads it.

Addresses
dockstore/dockstore:3654
https://ucsc-cgl.atlassian.net/browse/DOCK-1484

2020-09-11 17:32 UTC, NatalieEO approved these changes

2020-09-11 17:49 UTC, garyluu approved these changes

2020-09-11 23:57 UTC, coverbeck requested changes

2020-09-11 23:58 UTC, coverbeck commented
> dockstore/dockstore:3654

Syntax should be with a hash tag instead of a colon.

2020-09-14 15:51 UTC, wshands commented on dockstore-client/src/main/java/io/dockstore/client/cli/Client.java
> +                Runtime.getRuntime().exec(new String[] {file.toPath().toString(), "self-install"});
fixed; now uses Utilities.executeCommand

2020-09-14 19:21 UTC, coverbeck approved these changes

2020-09-14 20:02 UTC, merged